#[cfg(target_feature = "bmi2")]
use std::arch::x86_64::_pext_u64;

use crate::repr::bitboard::BB;

#[cfg(target_feature = "bmi2")]
pub fn pext_index(occupancy: BB, mask: BB) -> usize {
    unsafe { _pext_u64(occupancy.0, mask.0) as usize }
}

pub const PEXT_ROOK_BITS: [u8; 64] = [
    12, 11, 11, 11, 11, 11, 11, 12,
    11, 10, 10, 10, 10, 10, 10, 11,
    11, 10, 10, 10, 10, 10, 10, 11,
    11, 10, 10, 10, 10, 10, 10, 11,
    11, 10, 10, 10, 10, 10, 10, 11,
    11, 10, 10, 10, 10, 10, 10, 11,
    11, 10, 10, 10, 10, 10, 10, 11,
    12, 11, 11, 11, 11, 11, 11, 12,
];

pub const PEXT_BISHOP_BITS: [u8; 64] = [
    6, 5, 5, 5, 5, 5, 5, 6,
    5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 7, 7, 7, 7, 5, 5,
    5, 5, 7, 9, 9, 7, 5, 5,
    5, 5, 7, 9, 9, 7, 5, 5,
    5, 5, 7, 7, 7, 7, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5,
    6, 5, 5, 5, 5, 5, 5, 6,
];

const fn make_offsets_u32(bits: &[u8; 64]) -> [u32; 65] {
    let mut o = [0u32; 65];
    let mut i = 0;
    while i < 64 { o[i + 1] = o[i] + (1 << bits[i] as u32); i += 1; }
    o
}

const fn make_offsets_u16(bits: &[u8; 64]) -> [u16; 65] {
    let mut o = [0u16; 65];
    let mut i = 0;
    while i < 64 { o[i + 1] = o[i] + (1 << bits[i] as u16); i += 1; }
    o
}

pub const ROOK_OFFSETS:   [u32; 65] = make_offsets_u32(&PEXT_ROOK_BITS);
pub const BISHOP_OFFSETS: [u16; 65] = make_offsets_u16(&PEXT_BISHOP_BITS);
const TOTAL_ROOK_ENTRIES:   usize = ROOK_OFFSETS[64] as usize;
const TOTAL_BISHOP_ENTRIES: usize = BISHOP_OFFSETS[64] as usize;

pub const ROOK_BLOCKER_MASKS:   [u64; 64] = make_rook_blocker_masks();
pub const BISHOP_BLOCKER_MASKS: [u64; 64] = make_bishop_blocker_masks();
pub const ROOK_POST_MASKS:      [u64; 64] = make_rook_post_masks();
pub const BISHOP_POST_MASKS:    [u64; 64] = make_bishop_post_masks();

const fn make_rook_blocker_masks() -> [u64; 64] {
    let mut masks = [0u64; 64];
    let mut sq = 0usize;
    while sq < 64 {
        let rank = sq / 8;
        let file = sq % 8;
        let mut mask = 0u64;
        let mut r = 1usize;
        while r < 7 { if r != rank { mask |= 1u64 << (r * 8 + file); } r += 1; }
        let mut f = 1usize;
        while f < 7 { if f != file { mask |= 1u64 << (rank * 8 + f); } f += 1; }
        masks[sq] = mask;
        sq += 1;
    }
    masks
}

const fn make_bishop_blocker_masks() -> [u64; 64] {
    let mut masks = [0u64; 64];
    let mut sq = 0usize;
    while sq < 64 {
        let rank = (sq / 8) as i8;
        let file = (sq % 8) as i8;
        let mut mask = 0u64;
        let (mut r, mut f) = (rank + 1, file + 1);
        while r < 7 && f < 7 { mask |= 1u64 << (r * 8 + f) as u32; r += 1; f += 1; }
        let (mut r, mut f) = (rank + 1, file - 1);
        while r < 7 && f > 0 { mask |= 1u64 << (r * 8 + f) as u32; r += 1; f -= 1; }
        let (mut r, mut f) = (rank - 1, file + 1);
        while r > 0 && f < 7 { mask |= 1u64 << (r * 8 + f) as u32; r -= 1; f += 1; }
        let (mut r, mut f) = (rank - 1, file - 1);
        while r > 0 && f > 0 { mask |= 1u64 << (r * 8 + f) as u32; r -= 1; f -= 1; }
        masks[sq] = mask;
        sq += 1;
    }
    masks
}

const fn make_rook_post_masks() -> [u64; 64] {
    let mut masks = [0u64; 64];
    let mut sq = 0usize;
    while sq < 64 {
        let rank = sq / 8;
        let file = sq % 8;
        let mut mask = 0u64;
        let mut i = 0usize;
        while i < 8 {
            if i != rank { mask |= 1u64 << (i * 8 + file); }
            if i != file { mask |= 1u64 << (rank * 8 + i); }
            i += 1;
        }
        masks[sq] = mask;
        sq += 1;
    }
    masks
}

const fn make_bishop_post_masks() -> [u64; 64] {
    let mut masks = [0u64; 64];
    let mut sq = 0usize;
    while sq < 64 {
        let rank = (sq / 8) as i8;
        let file = (sq % 8) as i8;
        let mut mask = 0u64;
        macro_rules! ray {
            ($dr:expr, $df:expr) => {{
                let (mut r, mut f) = (rank + $dr, file + $df);
                while r >= 0 && r < 8 && f >= 0 && f < 8 {
                    mask |= 1u64 << (r * 8 + f) as u32;
                    r += $dr; f += $df;
                }
            }};
        }
        ray!( 1i8,  1i8); ray!( 1i8, -1i8);
        ray!(-1i8,  1i8); ray!(-1i8, -1i8);
        masks[sq] = mask;
        sq += 1;
    }
    masks
}

// Tables generated by build.rs — plain literal arrays, no const evaluation needed.
pub static ROOK_ATTACKS_FLAT:   [u16; TOTAL_ROOK_ENTRIES]   =
    include!(concat!(env!("OUT_DIR"), "/rook_attacks_flat.rs"));
pub static BISHOP_ATTACKS_FLAT: [u16; TOTAL_BISHOP_ENTRIES] =
    include!(concat!(env!("OUT_DIR"), "/bishop_attacks_flat.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use crate::repr::square::Square;
    use crate::movegen::tables::{rook_attacks_with_occupancy, bishop_attacks_with_occupancy};

    #[test]
    fn pext_works() {
        #[cfg(target_feature = "bmi2")]
        {
            let result = unsafe { _pext_u64(0b1010_1010, 0b1111_0000) };
            assert_eq!(result, 0b1010);
            println!("bmi2 is active, pext result = {result}");
        }
        #[cfg(not(target_feature = "bmi2"))]
        panic!("bmi2 is NOT enabled — check .cargo/config.toml");
    }

    #[test]
    fn flat_tables_round_trip() {
        use std::arch::x86_64::_pdep_u64;
        for sq in Square::all() {
            let i = sq as usize;
            let empty = BB::new(0);

            let idx = pext_index(empty, BB::new(ROOK_BLOCKER_MASKS[i]));
            let compressed = ROOK_ATTACKS_FLAT[ROOK_OFFSETS[i] as usize + idx];
            let attacks = BB::new(unsafe { _pdep_u64(compressed as u64, ROOK_POST_MASKS[i]) });
            let expected = rook_attacks_with_occupancy(sq, empty);
            assert!(attacks == expected, "rook round-trip failed at {}", sq.to_fen());

            let idx = pext_index(empty, BB::new(BISHOP_BLOCKER_MASKS[i]));
            let compressed = BISHOP_ATTACKS_FLAT[BISHOP_OFFSETS[i] as usize + idx];
            let attacks = BB::new(unsafe { _pdep_u64(compressed as u64, BISHOP_POST_MASKS[i]) });
            let expected = bishop_attacks_with_occupancy(sq, empty);
            assert!(attacks == expected, "bishop round-trip failed at {}", sq.to_fen());
        }
    }
}
